= DDD & Testing strategy

You're working in organization that fights fires in forest areas in a preventive way.

They manage several forest areas and want to use technology to improve their effectiveness.

The goal is to design some services that help to improve preparations before preventive works in the area itself.

Currently, they work on 3 specific areas:

[source,yaml]
----
- name: Calderona
  lat: 39.67
  lon: -0.43
  countryCode: ES
- name: Mariola
  lat: 38.72
  lon: -0.53
  countryCode: ES
- name: Penyagolosa
  lat: 40.23
  lon: -0.29
  countryCode: ES
----

== To do

. We need an endpoint to know the weather data of all managed locations

+
You can obtain the weather data from https://openweathermap.org/api[Open Weather Map API].

. Another one to tell us if the location is suitable to start working on it. They consider suitability depending on the weather. Good weather is needed and it's defined by `main` field from https://samples.openweathermap.org/data/2.5/weather?lat=35&lon=139&appid=b6907d289e10d714a6e88b30761fae22[_openweathermap_], when its value is equals `Clear`

. Organization is growing, so you need an API to manage new areas.

=== Goals

You should make focus on:

* Hexagonal architecture
* Domain Driven Design
* Testing techniques

xref:TECHNICAL.adoc[View technical info]
