= Technical aspects

== Design decisions

=== Technologies used

* Gradle (for building project)
* Kotlin (for production code)
* Groovy (for testing with Spock)
* PACT (for contract testing)
* Cucumber (for functional testing)
* WebFlux + Reactor (for reactive implementation)

=== Requirements

. Has at least JVM 17 to build and run the project

. You should set up you own OpenWeather APIKEY as an environment variable:

[source,shell script]
----
export OPEN_WEATHER_MAP_API_KEY=yourapikey
----

NOTE: You can create you onw key https://home.openweathermap.org/api_keys[here]

== Running

- To build the entire app with:

[source,shell]
----
./gradlew build
----

- To build the entire app but without running any tests:

[source,shell]
----
./gradlew build -x test -x contractTest
----

- To run _integration tests_:

[source,shell]
----
./gradlew integrationTests
----

- To run _contract tests_:

[source,shell]
----
./gradlew contractTest
----

- To run _functional tests_:

[source,shell]
----
./gradlew functionalTest
----

NOTE: Functional tests are running the entire app inside a docker container, so it requires a up & running docker environment

- To publish artifacts (including app fat jar and server stubs):

[source,shell]
----
./gradlew build publishToMavenLocal
----

- To run the entire app _in localhost_:

[source,shell]
----
./gradlew bootRun
----

Once up & running you can check and interact with the REST API using http://localhost:8080/swagger-ui.html[OpenAPI UI]

- To build a DOCKER image with the app fat jar:

[source,shell]
----
./gradlew app:bootBuildImage
----

=== Getting Technical Insights

- To print what will be the task graph planned by gradle when targeting a specific task:

[source,shell]
----
./gradlew tiTree [target task]
----

- To get dependencies report of every configuration set:

[source,shell]
----
./gradlew htmlDependencyReport
----

If you run app in DEV mode you can also see all insights offered by http://localhost:8080/actuator[actuator]:

[source,shell]
----
SPRING_PROFILES_ACTIVE=dev ./gradlew bootRun
----

=== KNOWN errors

* _Integration tests_ written using Spock are running during gradle `test` task instead of `integrationTest` task despite being correctly classified with tag `@Tag(TestClassification.INTEGRATION)`. As a workaround I'm using classification by name to distinguish them:
    - Unit tests named as `*Test`
    - Integration tests name as `*IT`

=== What could be improved?

* GITHUB base CI pipeline
* Providing _secrets_ in a secured way
* Use Factories for test data fixtures
* Embrace variability in tests (i.e.: _Time provider_, Variable Weather conditions)
* Review the possibility of https://springframework.guru/defining-spring-cloud-contracts-in-open-api/[mixing both Contract and API definition] as single source of truth
