= Technical aspects

== Design decisions

=== Technologies used

* Gradle (for building project)
* Kotlin (for production code)
* Groovy (for testing with Spock)
* Cucumber (for functional testing)
* PACT (for contract testing)
* WebFlux + Reactor (for reactive implementation)

=== Requirements

. Has at least JVM 17 to build and run the project

. You should set up you own OpenWeather APIKEY as an environment variable:

[source,shell script]
----
export OPEN_WEATHER_MAP_API_KEY=yourapikey
----

NOTE: You can create you onw key https://home.openweathermap.org/api_keys[here]

== Running

To build the entire app with:

[source,shell]
----
./gradlew build
----

To build the entire app but without running any tests:

[source,shell]
----
./gradlew build -x test -x contractTest
----

To publish artifacts (including app fat jar and server stubs):

[source,shell]
----
./gradlew build publishToMavenLocal
----

To run integration tests:

[source,shell]
----
./gradlew integrationTests
----

To run contract tests:

[source,shell]
----
./gradlew contractTest
----

To run functional tests:

[source,shell]
----
./gradlew functionalTest
----

NOTE: Requires application running on localhost

To run the entire app _in localhost_:

[source,shell]
----
./gradlew bootRun
----

Once up & running you can check and interact with the REST API using http://localhost:8080/swagger-ui.html[this web UI]:


=== Get Technical Insights

To print what will be the task graph planned by gradle when targeting a specific task:

[source,shell]
----
./gradlew tiTree [target task]
----

To get dependencies report of every configuration set:

[source,shell]
----
./gradlew htmlDependencyReport
----

=== KNOWN errors

* Integration tests written using Spock are running during gradle `test` task instead of `integrationTest` task despite being correctly classified with tag `@Tag(TestClassification.INTEGRATION)` (possible BUG on Spock - Gradle integration). As a workaround I'm using classification by name:
    - Unit tests named as `*Test`
    - Integration tests name as `*IT`

=== What could be improved?

* Docker file to containerize app
* GITHUB base CI pipeline
* Providing _secrets_ in a secured way
* Use Factories for test data fixtures
* Embrace variability (ie.: _Time provider_, Variable Weather conditions)
* Use `TestContainers` (to up &amp; run application) when running _Functional_ tests
* Review the possibility of https://springframework.guru/defining-spring-cloud-contracts-in-open-api/[mixing both Contract and API definition] as single source of truth
